//--------------------------------------------
// This file was autogenerated from: /home/howard/software/junction/cmake/junction_config.h.in
// while running: /home/howard/software/junction/CMakeLists.txt
// Do not edit!
//--------------------------------------------

#define JUNCTION_WITH_FOLLY 0
#define JUNCTION_WITH_CDS 0
#define JUNCTION_WITH_NBDS 0
#define JUNCTION_WITH_TBB 0
#define JUNCTION_WITH_TERVEL 0
#define JUNCTION_WITH_LIBCUCKOO 0
#define NBDS_USE_TURF_HEAP 0
#define TBB_USE_TURF_HEAP 0
#define JUNCTION_TRACK_GRAMPA_STATS 0
#define JUNCTION_USE_STRIPING 1

#include "junction_userconfig.h"
